# Generated by Django 5.2.17 on 2026-09-05 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='category_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.category'),
        ),
    ]
