# Generated by Django 5.2.17 on 2026-09-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expenses_category_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='category',
        ),
    ]
